import{a as w,S as v,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",q="52397534-5a81c9abe88dcfa16cadbb760";async function f(o,s=1){try{const t={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15};return(await w.get(S,{params:t})).data}catch(t){throw console.log("Error fetching images:",t),t}}const m=document.querySelector(".gallery"),d=document.querySelector(".loader"),P=new v(".gallery a",{captionData:"alt",captionDelay:250});function g(o){const s=o.map(({webformatURL:t,largeImageURL:a,tags:e,likes:r,views:i,comments:b,downloads:L})=>`
<li class="gallery-item">
<a class="gallery-link" href="${a}">
<img class="gallery-image" src="${t}" alt="${e}" loading="lazy">
</a>
<div class="info">
<p class="info-item"> <b>Likes</b> <span>${r}</span></p>
<p class="info-item"> <b>Views</b> <span>${i}</span></p>
<p class="info-item"> <b>Comments</b> <span>${b}</span></p>
<p class="info-item"> <b>Downloads</b> <span>${L}</span></p>
</div>
</li>
`).join("");m.insertAdjacentHTML("beforeend",s),P.refresh()}function E(){m.innerHTML=""}function h(){d&&d.classList.remove("hidden")}function y(){d&&d.classList.add("hidden")}const O=document.querySelector(".form"),c=document.querySelector(".load-more-btn");let l=1,p="",u=0;c.classList.add("hidden");O.addEventListener("submit",async o=>{o.preventDefault();const s=o.target.elements["search-text"].value.trim();if(!s){n.warning({title:"Oops",message:"Please enter a search term!",position:"topRight"});return}l=1,p=s,h(),E();try{const t=await f(p,l);if(u=t.totalHits,t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),u>15?c.classList.remove("hidden"):(c.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){n.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"}),console.log(t)}finally{y()}});c.addEventListener("click",async()=>{l+=1,h();try{const o=await f(p,l);g(o.hits),l*15>=u&&(c.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.log(o)}finally{y()}});
//# sourceMappingURL=index.js.map
