import{a as v,S,i as l}from"./assets/vendor-BSTwZ_tR.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",E="52397534-5a81c9abe88dcfa16cadbb760";async function h(o,s=1){try{const t={key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15};return(await v.get(q,{params:t})).data}catch(t){throw console.log("Error fetching images:",t),t}}const m=document.querySelector(".gallery"),d=document.querySelector(".loader"),P=new S(".gallery a",{captionData:"alt",captionDelay:250});function g(o){const s=o.map(({webformatURL:t,largeImageURL:i,tags:e,likes:r,views:n,comments:L,downloads:w})=>`
<li class="gallery-item">
<a class="gallery-link" href="${i}">
<img class="gallery-image" src="${t}" alt="${e}" loading="lazy">
</a>
<div class="info">
<p class="info-item"> <b>Likes</b> <span>${r}</span></p>
<p class="info-item"> <b>Views</b> <span>${n}</span></p>
<p class="info-item"> <b>Comments</b> <span>${L}</span></p>
<p class="info-item"> <b>Downloads</b> <span>${w}</span></p>
</div>
</li>
`).join("");m.insertAdjacentHTML("beforeend",s),P.refresh()}function H(){m.innerHTML=""}function y(){d&&d.classList.remove("hidden")}function b(){d&&d.classList.add("hidden")}const O=document.querySelector(".form"),a=document.querySelector(".load-more-btn"),u=document.querySelector(".search-btn");let c=1,f="",p=0;a.classList.add("hidden");O.addEventListener("submit",async o=>{o.preventDefault(),u.disabled=!0;const s=o.target.elements["search-text"].value.trim();if(!s){l.warning({title:"Oops",message:"Please enter a search term!",position:"topRight"}),u.disabled=!1;return}c=1,f=s,y(),H();try{const t=await h(f,c);if(p=t.totalHits,t.hits.length===0){l.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),p>15?a.classList.remove("hidden"):(a.classList.add("hidden"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){l.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"}),console.log(t)}finally{b(),u.disabled=!1}});a.addEventListener("click",async()=>{a.disabled=!0,c+=1,y();try{const o=await h(f,c);g(o.hits);const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),c*15>=p&&(a.classList.add("hidden"),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.log(o)}finally{b(),a.disabled=!1}});
//# sourceMappingURL=index.js.map
