import{a as q,S as B,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",P="52397534-5a81c9abe88dcfa16cadbb760";async function h(s,r=1){try{const t={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await q.get(E,{params:t})).data}catch(t){throw console.log("Error fetching images:",t),t}}const g=document.querySelector(".gallery"),c=document.querySelector(".loader"),y=document.querySelector(".load-more-btn"),$=new B(".gallery a",{captionData:"alt",captionDelay:250});function b(s){const r=s.map(({webformatURL:t,largeImageURL:a,tags:e,likes:o,views:i,comments:S,downloads:v})=>`
<li class="gallery-item">
<a class="gallery-link" href="${a}">
<img class="gallery-image" src="${t}" alt="${e}" loading="lazy">
</a>
<div class="info">
<p class="info-item"> <b>Likes</b> <span>${o}</span></p>
<p class="info-item"> <b>Views</b> <span>${i}</span></p>
<p class="info-item"> <b>Comments</b> <span>${S}</span></p>
<p class="info-item"> <b>Downloads</b> <span>${v}</span></p>
</div>
</li>
`).join("");g.insertAdjacentHTML("beforeend",r),$.refresh()}function H(){g.innerHTML=""}function L(){c&&c.classList.remove("hidden")}function w(){c&&c.classList.add("hidden")}function M(){y.classList.remove("hidden")}function m(){y.classList.add("hidden")}const O=document.querySelector(".form"),d=document.querySelector(".load-more-btn"),u=document.querySelector(".search-btn");let l=1,f="",p=0;m();O.addEventListener("submit",async s=>{s.preventDefault(),u.disabled=!0;const r=s.target.elements["search-text"].value.trim();if(!r){n.warning({title:"Oops",message:"Please enter a search term!",position:"topRight"}),u.disabled=!1;return}l=1,f=r,L(),H();try{const t=await h(f,l);if(p=t.totalHits,t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(t.hits),p>15?M():(m(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){n.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"}),console.log(t)}finally{w(),u.disabled=!1}});d.addEventListener("click",async()=>{d.disabled=!0,l+=1,L();try{const s=await h(f,l);b(s.hits);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),l*15>=p&&(m(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.log(s)}finally{w(),d.disabled=!1}});
//# sourceMappingURL=index.js.map
